/**
 * Note: This file was generated automatically, and will be
 * overwritten the next time "/parser/update.py" is executed.
 *
 *
 * DO NOT CHANGE THE DATA HERE!
 *
 * Instead, adjust "extractor.py" to correctly modify
 * the data while parsing.
 * 
 * 
 * Also make sure to keep "/js/logic.js" up to date
 * (especially the semesterManager)
 */

// semester name variables
const ss15    = "SS15",
      ws15_16 = "WS15/16",
      ss16    = "SS16",
      ws16_17 = "WS16/17",
      ss17    = "SS17",
      ws17_18 = "WS17/18";

// Vertiefungsgebiet name variables
const OSIS = "OSIS",
      SAMT = "SAMT",
      ISAE = "ISAE",
      HCGT = "HCGT",
      BPET = "BPET";

// actual data object
const data = {
    algoriddles: {
        kurz: "AlgoRiddles",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS, SAMT],
        cp: 3,
        vorher: [],
        dozent: ["Dr. Pascal Lenzner", "Dr. Timo Kötzing", "Prof. Dr. Tobias Friedrich"],
        nameLV: "Algorithmic Problem Solving"
    },
    aspektorientierteprogrammierung: {
        kurz: "Aspektorientierte<br />Programmierung",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss15],
        pflicht: false,
        empfohlen: "",
        vertiefung: [OSIS, SAMT],
        cp: 3,
        vorher: [],
        dozent: ["Prof. Dr. Robert Hirschfeld"],
        nameLV: "Aspektorientierte Programmierung"
    },
    bdanalytics: {
        kurz: "BD Analytics",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["SB2", "Vertiefungsgebiete"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Emmanuel Müller"],
        nameLV: "Big Data Analytics"
    },
    bdanalyticslab: {
        kurz: "BD Analytics Lab",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss16, ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Erik Scharwächter", "Fabian Geier", "Prof. Dr. Emmanuel Müller"],
        nameLV: "Big Data Analytics Lab"
    },
    bdsecurityanalytics: {
        kurz: "BD Security Analytics",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Dr. Feng Cheng"],
        nameLV: "Big Data Security Analytics"
    },
    beautifuldata: {
        kurz: "Beautiful Data",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, OSIS],
        cp: 3,
        vorher: [],
        dozent: ["Prof. Dr. Felix Naumann"],
        nameLV: "Beautiful Data"
    },
    bildundvideoprozessierung: {
        kurz: "Bild- und<br />Videoprozessierung",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws15_16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Dr. Matthias Trapp"],
        nameLV: "Bild- und Videoprozessierung mit OpenGL ES für Mobile Geräte"
    },
    blockkursibmpowersystems: {
        kurz: "Blockkurs \"IBM<br />Power Systems\"",
        lehrform: ["Blockseminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws16_17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Andreas Polze"],
        nameLV: "Blockkurs \\&quot;IBM Power Systems\\&quot;"
    },
    bpminthecloud: {
        kurz: "BPM in the Cloud",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss15],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Adriatik Nikaj", "Marcin Hewelt", "Prof. Dr. Mathias Weske"],
        nameLV: "BPM in the Cloud: From t.BPM and App development"
    },
    bs: {
        kurz: "BS",
        lehrform: ["Vorlesung"],
        modul: ["BS"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: true,
        empfohlen: 3,
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Andreas Polze"],
        nameLV: "Betriebssysteme 1"
    },
    bs2: {
        kurz: "BS II",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss15, ss16, ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Andreas Grapentin", "Frank Feinbube", "Prof. Dr. Andreas Polze"],
        nameLV: "Betriebssysteme II"
    },
    businesseventprocessing: {
        kurz: "Business Event Processing",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss16, ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Kimon Batoulis", "Luise Pufahl", "Prof. Dr. Dimka Karastoyanova"],
        nameLV: "Business Event Processing"
    },
    businessprocesssimulation: {
        kurz: "Business Process<br />Simulation",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Luise Pufahl", "Prof. Dr. Mathias Weske"],
        nameLV: "Business Process Simulation"
    },
    bva: {
        kurz: "BVA",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws16_17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Dr. Matthias Trapp"],
        nameLV: "Bildverarbeitungsalgorithmen"
    },
    cg1: {
        kurz: "CG I",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["SB1", "Vertiefungsgebiete"],
        semester: [ss15, ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Jürgen Döllner"],
        nameLV: "3D-Computergrafik I"
    },
    cg2: {
        kurz: "CG II",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss16, ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Jürgen Döllner"],
        nameLV: "3D-Computergrafik II"
    },
    clientseitigewebprogrammierung: {
        kurz: "Clientseitige<br />Webprogrammierung",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Christoph Meinel"],
        nameLV: "Clientseitige Webprogrammierung"
    },
    comprog: {
        kurz: "ComProg",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss16, ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Dr. Pascal Lenzner", "Prof. Dr. Tobias Friedrich"],
        nameLV: "Competitive Programming"
    },
    copsandrobbers: {
        kurz: "Cops and Robbers",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss15, ss16, ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Dr. Feng Cheng", "Prof. Dr. Christoph Meinel"],
        nameLV: "Cops and Robbers"
    },
    dataengineeringinderpraxis: {
        kurz: "Data Engineering<br />in der Praxis",
        lehrform: ["Vorlesung"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, OSIS],
        cp: 3,
        vorher: [],
        dozent: ["Dr. Matthias Uflacker", "Dr. Ralf Krestel", "Prof. Dr. Emmanuel Müller", "Prof. Dr. Felix Naumann"],
        nameLV: "Data Engineering in der Praxis - Ringvorlesung"
    },
    dbs1: {
        kurz: "DBS I",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["SB2", "Vertiefungsgebiete"],
        semester: [ss15, ss16, ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Felix Naumann", "Thorsten Papenbrock"],
        nameLV: "Datenbanksysteme I"
    },
    dbs2: {
        kurz: "DBS II",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws15_16, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Felix Naumann"],
        nameLV: "Datenbanksysteme II"
    },
    diskretestrukturen: {
        kurz: "Diskrete Strukturen",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws16_17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS, SAMT],
        cp: 3,
        vorher: [],
        dozent: ["Dr. Timo Kötzing", "Prof. Dr. Tobias Friedrich"],
        nameLV: "Diskrete Strukturen"
    },
    dschooladvancedtrack: {
        kurz: "D-School Advanced Track",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Softskills"],
        semester: [ss15, ss16, ss17, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [],
        cp: 9,
        vorher: [],
        dozent: ["Dr. Claudia Nicolai", "Prof. Ulrich Weinberg"],
        nameLV: "D-School Advanced Track"
    },
    dschoolbasictrack: {
        kurz: "D-School Basic Track",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Softskills"],
        semester: [ss15, ss16, ss17, ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [],
        cp: 9,
        vorher: [],
        dozent: ["Dr. Claudia Nicolai", "Prof. Ulrich Weinberg"],
        nameLV: "D-School Basic Track"
    },
    dschoolfirsttrack: {
        kurz: "D-School First Track",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Softskills"],
        semester: [ss15, ss16, ss17, ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [],
        cp: 3,
        vorher: [],
        dozent: ["Dr. Claudia Nicolai", "Prof. Ulrich Weinberg"],
        nameLV: "Einführung in Design Thinking: From Inspirations to Ideas"
    },
    einfuehrungindiealgorithmik: {
        kurz: "Einführung in<br />die Algorithmik",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws15_16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Dr. Pascal Lenzner", "Prof. Dr. Tobias Friedrich"],
        nameLV: "Einführung in die Algorithmik"
    },
    einfuehrunginformationsvisualisierung: {
        kurz: "Einführung<br />Informationsvisualisierung",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Jürgen Döllner"],
        nameLV: "Einführung Informationsvisualisierung"
    },
    einfuehrunginvisualanalytics: {
        kurz: "Einführung in<br />Visual Analytics",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Jürgen Döllner"],
        nameLV: "Einführung in Visual Analytics"
    },
    englischlevel1: {
        kurz: "Englisch (Level 1)",
        lehrform: ["Seminar"],
        modul: ["Softskills"],
        semester: [ss15, ss16, ss17, ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [],
        cp: 3,
        vorher: [],
        dozent: ["David Meier"],
        nameLV: "Fachspezifisches Englisch (Level 1)"
    },
    englischlevel2: {
        kurz: "Englisch (Level 2)",
        lehrform: ["Seminar"],
        modul: ["Softskills"],
        semester: [ss15, ss16, ss17, ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [],
        cp: 3,
        vorher: [],
        dozent: ["David Meier"],
        nameLV: "Fachspezifisches Englisch (Level 2)"
    },
    eventdrivencasemanagement: {
        kurz: "Event-driven<br />Case Management",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Marcin Hewelt", "Prof. Dr. Matthias Weidlich"],
        nameLV: "Event-driven Case Management"
    },
    gds: {
        kurz: "GdS",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Grundlagen IT-Systems Engineering"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: true,
        empfohlen: 1,
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Dr.-Ing. Ralf Wollowski"],
        nameLV: "Grundlagen digitaler Systeme"
    },
    grafikprogramming: {
        kurz: "Grafikprogramming",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, ISAE],
        cp: 6,
        vorher: [],
        dozent: ["Daniel Limberger", "Prof. Dr. Jürgen Döllner", "Stefan Buschmann"],
        nameLV: "Grafikprogramming mit OpenGL und C++"
    },
    graphentheorie: {
        kurz: "Graphentheorie",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS, SAMT],
        cp: 3,
        vorher: [],
        dozent: ["Prof. Dr. Tobias Friedrich"],
        nameLV: "Graphentheorie"
    },
    handsoncodingexercisesinlargescalelearni: {
        kurz: "Hands-On Coding Exercises<br />in Large Scale Learni...",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws16_17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Christoph Meinel"],
        nameLV: "Hands-On Coding Exercises in Large Scale Learning Environments"
    },
    hci1: {
        kurz: "HCI I",
        lehrform: ["Vorlesung"],
        modul: ["SB4", "Vertiefungsgebiete"],
        semester: [ws15_16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Patrick Baudisch"],
        nameLV: "Designing Interactive Systems"
    },
    hci2: {
        kurz: "HCI II",
        lehrform: ["Vorlesung"],
        modul: ["SB4", "Vertiefungsgebiete"],
        semester: [ss15, ss17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Patrick Baudisch"],
        nameLV: "Building Interactive Devices"
    },
    hcipsaugmentrealityvirtualrealityand: {
        kurz: "[HCI PS] Augment Reality,<br />Virtual Reality, and ...",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Patrick Baudisch"],
        nameLV: "HCI Project Seminar Augment Reality, Virtual Reality, and Personal Fabrication"
    },
    hcipsbuildinginteractivesystemsbasedon: {
        kurz: "[HCI PS] Building Interactive<br />Systems based on ...",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws15_16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Patrick Baudisch"],
        nameLV: "HCI Project Seminar: Building Interactive Systems based on Fabrication and Haptics"
    },
    hcipsbuildinginteractivesystemsfrom3dp: {
        kurz: "[HCI PS] Building Interactive<br />Systems from 3D-P...",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss15],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Patrick Baudisch"],
        nameLV: "HCI Project Seminar on Building Interactive Systems from 3D-Printers"
    },
    hcipspersonalfabricationandhaptics: {
        kurz: "[HCI PS] Personal<br />Fabrication and Haptics",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws16_17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Patrick Baudisch"],
        nameLV: "HCI Project Seminar Personal Fabrication and Haptics"
    },
    hcipspersonalfabricationandinteraction: {
        kurz: "[HCI PS] Personal<br />Fabrication and Interaction",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Patrick Baudisch"],
        nameLV: "HCI Project Seminar Personal Fabrication and Interaction"
    },
    hcipsroboticscodeand3dprinting: {
        kurz: "[HCI PS] Robotics,<br />Code, and 3D Printing",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Patrick Baudisch"],
        nameLV: "HCI Project Seminar on Robotics, Code, and 3D Printing"
    },
    historyofprogramminglanguages: {
        kurz: "History of<br />Programming Languages",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [SAMT],
        cp: 3,
        vorher: [],
        dozent: ["Johannes Henning", "Marcel Taeumel", "Prof. Dr. Robert Hirschfeld", "Toni Mattis"],
        nameLV: "History of Programming Languages"
    },
    identitaetsmanagement: {
        kurz: "Identitätsmanagement",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Christoph Meinel"],
        nameLV: "Identitätsmanagement"
    },
    informationvisualisationtechniques: {
        kurz: "Information<br />Visualisation Techniques",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Jürgen Döllner"],
        nameLV: "Information Visualisation Techniques for Industrie 4.0"
    },
    isec: {
        kurz: "ISec",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Christoph Meinel"],
        nameLV: "Internet-Security - Weaknesses and Targets"
    },
    knowledgediscovery: {
        kurz: "Knowledge Discovery",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws16_17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, ISAE, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Dr. rer. nat. Harald Sack"],
        nameLV: "Knowledge Discovery with Linked Data"
    },
    knowledgemining: {
        kurz: "Knowledge Mining",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss15, ss16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, ISAE, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Dr. rer. nat. Harald Sack"],
        nameLV: "Knowledge Mining"
    },
    lerntechnikenundstrategien: {
        kurz: "Lerntechniken<br />und Strategien",
        lehrform: ["Seminar"],
        modul: ["Softskills"],
        semester: [ss17, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [],
        cp: 3,
        vorher: [],
        dozent: ["Dr. Christiane Potzner"],
        nameLV: "Lerntechniken und Strategien zur Prüfungsvorbereitung"
    },
    linux: {
        kurz: "Linux",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Christoph Meinel"],
        nameLV: "Linux for the Masses"
    },
    mathematik1: {
        kurz: "Mathematik I",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Mathematische und theoretische Grundlagen"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: true,
        empfohlen: 1,
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Christoph Meinel"],
        nameLV: "Mathematik I - Diskrete Strukturen und Logik"
    },
    mathematik2: {
        kurz: "Mathematik II",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Mathematische und theoretische Grundlagen"],
        semester: [ss15, ss16, ss17],
        pflicht: true,
        empfohlen: 2,
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Dr. habil. Ferdinand Börner"],
        nameLV: "Mathematik II"
    },
    mod1: {
        kurz: "Mod I",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Softwaretechnik und Modellierung"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: true,
        empfohlen: 1,
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Joachim Hänsel", "Maria Maximova", "Prof. Dr. Holger Giese"],
        nameLV: "Modellierung I"
    },
    mod2: {
        kurz: "Mod II",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Softwaretechnik und Modellierung"],
        semester: [ss15, ss16, ss17],
        pflicht: true,
        empfohlen: 2,
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Holger Giese"],
        nameLV: "Modellierung II"
    },
    openhpi: {
        kurz: "openHPI",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws15_16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Jan Renz", "Prof. Dr. Christoph Meinel", "Thomas Staubitz"],
        nameLV: "openHPI: Web Accessibility - Opening up web applacations for everyone"
    },
    pem: {
        kurz: "PEM",
        lehrform: ["Projekt", "Seminar"],
        modul: ["PEM"],
        semester: [ss15, ss16, ss17, ws15_16, ws16_17, ws17_18],
        pflicht: true,
        empfohlen: "",
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Peter Göttel"],
        nameLV: "Projektentwicklung und- Management: Teammanagement und Softskills in Projekten"
    },
    pois: {
        kurz: "POIS",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["SB3", "Vertiefungsgebiete"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Kimon Batoulis", "Prof. Dr. Mathias Weske"],
        nameLV: "Prozessorientierte Informationssysteme"
    },
    pois2: {
        kurz: "POIS II",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss15],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Mathias Weske"],
        nameLV: "Prozessorientierte Informationssysteme II"
    },
    privacyinpublicclouds: {
        kurz: "Privacy in Public Clouds",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss15, ss16, ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, ISAE, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Christoph Meinel"],
        nameLV: "Privacy in Public Clouds"
    },
    processesanddecisionsinthecloud: {
        kurz: "Processes and<br />Decisions in the Cloud",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Kimon Batoulis", "Prof. Dr. Mathias Weske"],
        nameLV: "Processes and Decisions in the Cloud"
    },
    professionalisiertelerntechniken: {
        kurz: "Professionalisierte<br />Lerntechniken",
        lehrform: ["Seminar"],
        modul: ["Softskills"],
        semester: [ss15, ss16, ws15_16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [],
        cp: 3,
        vorher: [],
        dozent: ["Dr. Rolf Specht"],
        nameLV: "Professionalisierte Lerntechniken"
    },
    programmierungcomputergrafischerverfahren: {
        kurz: "Programmierung<br />computergrafischer Verfahren",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss15],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Jürgen Döllner"],
        nameLV: "Programmierung computergrafischer Verfahren mit C++und OpenGL"
    },
    programminglanguages: {
        kurz: "Programming Languages",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Johannes Henning", "Patrick Rein", "Prof. Dr. Robert Hirschfeld", "Stefan Ramson", "Toni Mattis"],
        nameLV: "Programming Languages: Design and Implementation"
    },
    pt1: {
        kurz: "PT I",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Grundlagen IT-Systems Engineering"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: true,
        empfohlen: 1,
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Andreas Polze"],
        nameLV: "Einführung in die Programmiertechnik I"
    },
    pt2: {
        kurz: "PT II",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Grundlagen IT-Systems Engineering"],
        semester: [ss15, ss16, ss17],
        pflicht: true,
        empfohlen: 2,
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Johannes Wolf", "Prof. Dr. Jürgen Döllner"],
        nameLV: "Einführung in die Programmiertechnik II"
    },
    recht1: {
        kurz: "Recht I",
        lehrform: ["Vorlesung"],
        modul: ["Rechtliche und wirtschaftliche Grundlagen"],
        semester: [ss15, ss16, ss17],
        pflicht: true,
        empfohlen: 2,
        vertiefung: [],
        cp: 3,
        vorher: [],
        dozent: ["Dr. Timm Krohn"],
        nameLV: "Recht für Ingenieure I"
    },
    recht2: {
        kurz: "Recht II",
        lehrform: ["Vorlesung"],
        modul: ["Rechtliche und wirtschaftliche Grundlagen"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: true,
        empfohlen: 3,
        vertiefung: [],
        cp: 3,
        vorher: [],
        dozent: ["Dr. Timm Krohn", "Prof. Dr. Jan Eickelberg"],
        nameLV: "Recht für Ingenieure II - Rechtsfragen der Digitalisierung im Geschäftsverkehr"
    },
    securecoding: {
        kurz: "Secure Coding",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss15],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Christoph Meinel"],
        nameLV: "Secure Coding"
    },
    semanticmediamining: {
        kurz: "Semantic Media Mining",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws15_16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Dr. rer. nat. Harald Sack"],
        nameLV: "Semantic Media Mining"
    },
    seminarraeumlichedatenundraumzeitlichedaten: {
        kurz: "Seminar Räumliche Daten<br />und raumzeitliche Daten",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws15_16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Jürgen Döllner"],
        nameLV: "Seminar Räumliche Daten und raumzeitliche Daten"
    },
    softwaremodularitaet: {
        kurz: "Softwaremodularität",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws16_17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Johannes Henning", "Marcel Taeumel", "Prof. Dr. Robert Hirschfeld", "Stefan Ramson", "Toni Mattis"],
        nameLV: "Softwaremodularität"
    },
    stubs: {
        kurz: "StubS",
        lehrform: ["Seminar"],
        modul: [],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [],
        cp: 0,
        vorher: [],
        dozent: ["Dr.-Ing. Ralf Wollowski"],
        nameLV: "Studienbegleitendes Seminar"
    },
    swa: {
        kurz: "SWA",
        lehrform: ["Vorlesung"],
        modul: ["Grundlagen IT-Systems Engineering"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: 3,
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Jens Lincke", "Johannes Henning", "Marcel Taeumel", "Patrick Rein", "Prof. Dr. Robert Hirschfeld", "Stefan Ramson", "Tobias Pape", "Toni Mattis"],
        nameLV: "Softwarearchitektur"
    },
    swqualitaet: {
        kurz: "SWQualität",
        lehrform: ["Projekt", "Vorlesung"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws15_16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Joachim Hänsel", "Prof. Dr. Holger Giese"],
        nameLV: "Softwarequalität"
    },
    swt1: {
        kurz: "SWT I",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Softwaretechnik und Modellierung"],
        semester: [ss15, ss16, ss17],
        pflicht: false,
        empfohlen: 4,
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Jens Lincke", "Johannes Henning", "Marcel Taeumel", "Patrick Rein", "Prof. Dr. Robert Hirschfeld", "Stefan Ramson", "Tim Felgentreff", "Tobias Pape", "Toni Mattis"],
        nameLV: "Softwaretechnik I"
    },
    swt2: {
        kurz: "SWT II",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Dr. Matthias Uflacker"],
        nameLV: "Softwaretechnik II - Agile Software Development in Large Teams"
    },
    testdrivenlearningassignments: {
        kurz: "Test-Driven Learning<br />Assignments",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Christiane Hagedorn", "Prof. Dr. Christoph Meinel", "Ralf Teusner", "Thomas Staubitz"],
        nameLV: "Test-Driven Learning Assignments"
    },
    textmining: {
        kurz: "Text Mining",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS],
        cp: 3,
        vorher: [],
        dozent: ["Dr. Ralf Krestel"],
        nameLV: "Text Mining"
    },
    ti1: {
        kurz: "TI I",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Mathematische und theoretische Grundlagen"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: true,
        empfohlen: 3,
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Tobias Friedrich"],
        nameLV: "Theoretische Informatik I"
    },
    ti2: {
        kurz: "TI II",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["Mathematische und theoretische Grundlagen"],
        semester: [ss15, ss16, ss17],
        pflicht: true,
        empfohlen: 4,
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Tobias Friedrich"],
        nameLV: "Theoretische Informatik II"
    },
    ueberzeugendpraesentieren: {
        kurz: "Überzeugend<br />Präsentieren",
        lehrform: ["Blockseminar"],
        modul: ["Softskills"],
        semester: [ss15, ss16, ss17, ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [],
        cp: 3,
        vorher: [],
        dozent: ["Dr. Werner Dieball"],
        nameLV: "Überzeugend Präsentieren - der erste Eindruck zählt"
    },
    unternehmensanwendungen: {
        kurz: "Unternehmensanwendungen",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss15, ss16, ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, OSIS],
        cp: 6,
        vorher: [],
        dozent: ["Dr. Matthias Uflacker"],
        nameLV: "Unternehmensanwendungen: Prozesse, Modelle und Implementierung"
    },
    vhdl: {
        kurz: "VHDL",
        lehrform: ["Vorlesung"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss16],
        pflicht: false,
        empfohlen: "",
        vertiefung: [OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Dr.-Ing. Ralf Wollowski"],
        nameLV: "Entwurf und Implementierung digitaler Schaltungen mit VHDL"
    },
    wahrscheinlichkeitstheorie: {
        kurz: "Wahrscheinlichkeitstheorie",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS, SAMT],
        cp: 3,
        vorher: [],
        dozent: ["Dr. Timo Kötzing"],
        nameLV: "Wahrscheinlichkeitstheorie"
    },
    webprogrammierungundwebframeworks: {
        kurz: "Web-Programmierung<br />und Web-Frameworks",
        lehrform: ["Projekt", "Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: false,
        empfohlen: "",
        vertiefung: [BPET, ISAE, OSIS, SAMT],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Christoph Meinel"],
        nameLV: "Web-Programmierung und Web-Frameworks"
    },
    weiterfuehrendethemenzuwww: {
        kurz: "Weiterführende<br />Themen zu WWW",
        lehrform: ["Seminar"],
        modul: ["Vertiefungsgebiete"],
        semester: [ss15, ss16, ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [ISAE, OSIS, SAMT],
        cp: 3,
        vorher: [],
        dozent: ["Prof. Dr. Christoph Meinel"],
        nameLV: "Weiterführende Themen zu Internet- und WWW-Technologien"
    },
    wirtschaft: {
        kurz: "Wirtschaft",
        lehrform: ["Vorlesung"],
        modul: ["Rechtliche und wirtschaftliche Grundlagen"],
        semester: [ws15_16, ws16_17, ws17_18],
        pflicht: true,
        empfohlen: 1,
        vertiefung: [],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Katharina Hölzle"],
        nameLV: "Wirtschaftliche Grundlagen"
    },
    www: {
        kurz: "WWW",
        lehrform: ["Vorlesung", "Übung"],
        modul: ["SB5", "Vertiefungsgebiete"],
        semester: [ss15, ss16, ss17],
        pflicht: false,
        empfohlen: "",
        vertiefung: [HCGT, ISAE],
        cp: 6,
        vorher: [],
        dozent: ["Prof. Dr. Christoph Meinel"],
        nameLV: "Internet- und WWW-Technologien"
    },
};
